name: app_database
description: Local Database
version: 0.0.1
homepage: null

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  drift: ^2.1.0
  flutter:
    sdk: flutter
  path: ^1.8.2
  path_provider: ^2.0.11
  sqlite3_flutter_libs: ^0.5.12

dev_dependencies:
  build_runner: ^2.3.0
  drift_dev: ^2.1.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0

flutter: null
