name: moneymanager
description: Money Manager
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  app_database:
    path: packages/app_database
  bloc: ^8.1.0
  cupertino_icons: ^1.0.2
  dynamic_color: ^1.5.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: ^10.3.0
  fpdart: ^0.3.0
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  go_router: ^5.2.4
  injectable: ^2.1.0
  intl: ^0.17.0

dev_dependencies:
  bloc_test: ^9.1.0
  build_runner: ^2.3.0
  flutter_test:
    sdk: flutter
  freezed: ^2.2.0
  injectable_generator: ^2.1.3
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
